"""Initial migration

Revision ID: 9eec2db0741e
Revises: 
Create Date: 2026-02-02 03:02:04.324913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eec2db0741e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('mandi_name', sa.String(length=100), nullable=False),
    sa.Column('crop_name', sa.String(length=50), nullable=False),
    sa.Column('price_per_quintal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('location_lng', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('previous_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_change_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_crop_name'), 'market_prices', ['crop_name'], unique=False)
    op.create_index(op.f('ix_market_prices_date'), 'market_prices', ['date'], unique=False)
    op.create_index(op.f('ix_market_prices_district'), 'market_prices', ['district'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_mandi_name'), 'market_prices', ['mandi_name'], unique=False)
    op.create_index(op.f('ix_market_prices_state'), 'market_prices', ['state'], unique=False)
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('location_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('location_lng', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('crops', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('notification_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_message_id', sa.String(length=100), nullable=True),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_history_channel'), 'notification_history', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_history_delivery_status'), 'notification_history', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    op.create_index(op.f('ix_notification_history_notification_type'), 'notification_history', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_msp_updates', sa.Boolean(), nullable=False),
    sa.Column('weather_alerts', sa.Boolean(), nullable=False),
    sa.Column('scheme_notifications', sa.Boolean(), nullable=False),
    sa.Column('market_price_alerts', sa.Boolean(), nullable=False),
    sa.Column('preferred_channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=False),
    sa.Column('notification_language', sa.String(length=10), nullable=True),
    sa.Column('custom_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_channel'), 'sessions', ['channel'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_last_activity'), 'sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_activity'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_channel'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_notification_type'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_delivery_status'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_channel'), table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_prices_state'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_mandi_name'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_district'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_name'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
